---
name: "Master Workflow"
env:
  DOCKER_USER: emranbm
  IMAGE_NAME: emranbm/jsmtproxy:latest
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKER_HUB_TOKEN }} | docker login -u $DOCKER_USER --password-stdin
      - name: Build Image
        run: docker build -t $IMAGE_NAME .
      - name: Push Image
        run: docker push $IMAGE_NAME
